### ISSUE TITLE
update js path

### ISSUE THREAD

**Issue by le9i0nx** [le9i0nx/ansible-proxmox#5]
to do both options path to the file.

``` yaml
TASK [le9i0nx.proxmox : install required packages] *****************************
ok: [pve32.pve.mpautina.ru] => (item=[u'postfix', u'ksm-control-daemon', u'open-iscsi', u'proxmox-ve', u'patch'])
ok: [pve6.pve.mpautina.ru] => (item=[u'postfix', u'ksm-control-daemon', u'open-iscsi', u'proxmox-ve', u'patch'])
ok: [pve02.pve.mpautina.ru] => (item=[u'postfix', u'ksm-control-daemon', u'open-iscsi', u'proxmox-ve', u'patch'])
ok: [pve29.pve.mpautina.ru] => (item=[u'postfix', u'ksm-control-daemon', u'open-iscsi', u'proxmox-ve', u'patch'])
ok: [pve59.pve.mpautina.ru] => (item=[u'postfix', u'ksm-control-daemon', u'open-iscsi', u'proxmox-ve', u'patch'])
ok: [pve34.pve.mpautina.ru] => (item=[u'postfix', u'ksm-control-daemon', u'open-iscsi', u'proxmox-ve', u'patch'])

TASK [le9i0nx.proxmox : install pip proxmoxer] *********************************
ok: [pve32.pve.mpautina.ru]
ok: [pve6.pve.mpautina.ru]
ok: [pve02.pve.mpautina.ru]
ok: [pve34.pve.mpautina.ru]
ok: [pve29.pve.mpautina.ru]
ok: [pve59.pve.mpautina.ru]

TASK [le9i0nx.proxmox : apply patch] *******************************************
fatal: [pve32.pve.mpautina.ru]: FAILED! => {"changed": false, "failed": true, "msg": "dest /usr/share/pve-manager/ext6/pvemanagerlib.js doesn't exist or not writable"}
fatal: [pve6.pve.mpautina.ru]: FAILED! => {"changed": false, "failed": true, "msg": "dest /usr/share/pve-manager/ext6/pvemanagerlib.js doesn't exist or not writable"}
ok: [pve59.pve.mpautina.ru]
ok: [pve02.pve.mpautina.ru]
ok: [pve34.pve.mpautina.ru]
ok: [pve29.pve.mpautina.ru]
```
